# Generated by Django 4.0.1 on 2022-01-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='RowingSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('com_port', models.CharField(max_length=50)),
                ('c', models.CharField(max_length=5)),
                ('t', models.CharField(max_length=5)),
                ('version', models.CharField(max_length=50)),
                ('max_level', models.IntegerField(default=0)),
                ('h', models.CharField(max_length=5)),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('end_time', models.DateTimeField(verbose_name='end_time')),
            ],
        ),
        migrations.CreateModel(
            name='RowingStroke',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('t', models.CharField(max_length=5)),
                ('distance', models.FloatField(default=0)),
                ('one', models.IntegerField(default=1)),
                ('speed', models.TimeField()),
                ('strokes_per_minute', models.IntegerField(default=0)),
                ('watts', models.IntegerField(default=0)),
                ('colories_per_hour', models.IntegerField(default=0)),
                ('zero', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(verbose_name='time_stamp')),
                ('rowing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowing.rowingsession')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowing.question')),
            ],
        ),
    ]
