# Generated by Django 4.0.1 on 2022-01-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowingstroke',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rowingstroke',
            name='t',
            field=models.IntegerField(max_length=5),
        ),
    ]
