# Generated by Django 4.0.1 on 2022-01-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0003_alter_rowingstroke_distance_alter_rowingstroke_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowingstroke',
            name='t',
            field=models.IntegerField(),
        ),
    ]
