# Generated by Django 4.0.1 on 2022-01-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0004_alter_rowingstroke_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowingsession',
            name='h',
            field=models.IntegerField(default=0),
        ),
    ]
