# Generated by Django 4.0.1 on 2022-01-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0005_alter_rowingsession_h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowingsession',
            name='t',
            field=models.IntegerField(default=0),
        ),
    ]
