# Generated by Django 4.0.1 on 2022-01-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0006_alter_rowingsession_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowingsession',
            name='c',
            field=models.IntegerField(default=0),
        ),
    ]
