# Generated by Django 4.0.1 on 2022-01-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0007_alter_rowingsession_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowingsession',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
