# Generated by Django 4.0.1 on 2022-01-17 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0008_rowingsession_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowingsession',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
