# Generated by Django 4.0.1 on 2022-01-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comport', models.CharField(max_length=50)),
                ('c', models.CharField(max_length=5)),
                ('t', models.CharField(max_length=5)),
                ('version', models.CharField(max_length=50)),
                ('max_level', models.IntegerField(default=0)),
                ('h', models.CharField(max_length=5)),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('end_time', models.DateTimeField(verbose_name='end_time')),
            ],
        ),
        migrations.CreateModel(
            name='RowingStroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=5)),
                ('distance', models.FloatField(default=0)),
                ('one', models.IntegerField(default=1)),
                ('speed', models.TimeField()),
                ('strokes_per_minute', models.IntegerField(default=0)),
                ('watts', models.IntegerField(default=0)),
                ('colories_per_hour', models.IntegerField(default=0)),
                ('zero', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(verbose_name='time_stamp')),
                ('rowing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.rowingsession')),
            ],
        ),
    ]
