# Generated by Django 4.0.1 on 2022-01-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rowingsession_rowingstroke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rowingsession',
            old_name='comport',
            new_name='com_port',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='rowingsession',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rowingstroke',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
